#!/bin/bash
cargo build --release --manifest-path=ray-tracer-slave/Cargo.toml && \
  cargo build --release --manifest-path=ray-tracer-controller/Cargo.toml && \
  cp ray-tracer-controller/target/release/ray-tracer-controller docker/master/ && \
  cp ray-tracer-slave/target/release/ray-tracer-slave docker/slave/ && \
  cd docker && \
  docker compose -f docker-stack.yaml up -d && \
  echo "Deployment completed successfully" || \
  echo "Deployment Failed!"
