services:
  master:
    build: ./master
    ports:
      - "8080:8080"
    networks:
      - raynet
    
  slave:
    build: ./slave
    ports:
      - "8081:8081"
    networks:
      - raynet

networks:
  raynet:
