services:
  master:
    build: ./master
    ports:
      - "8080:8080"
    networks:
      - raynet
    
  slave:
    build: ./slave
    ports:
      - "8081:8081"
    networks:
      - raynet

networks:
  raynet:

# version: "3.9"

# services:

#   master:
#     image: sculpordwarftongue/ray-tracer-controller:2
#     ports:
#       - "8080:8080"
#     environment:
#       NODE_NAME: "{{.Node.Hostname}}"


#   slave:
#     image: sculpordwarftongue/ray-tracer-slave:2
#     ports:
#       - "8081:8081"
#     deploy:
#       replicas: 2
#     environment:
#       NODE_NAME: "{{.Node.Hostname}}"
